#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

#include <ft2build.h>
#include FT_FREETYPE_H

#define ASCII_MAX 128

int main(int argc, char* argv[])
{
    if (argc != 3)
    {
        printf("Usage: %s <font-file> <font-size>\n", argv[0]);
        printf("       %s FreeMono.ttf 16\n", argv[0]);
        return EXIT_FAILURE;
    }

    // 初始化 FreeType 库
    FT_Library  library;
    FT_Error err = FT_Init_FreeType(&library);
    if (err != FT_Err_Ok)
    {
        fprintf(stderr, "%d %s\n", err, FT_Error_String(err));
        return EXIT_FAILURE;
    }

    // 加载字体
    FT_Face face;
    err = FT_New_Face(library, argv[1], 0, &face);
    if (err != FT_Err_Ok)
    {
        fprintf(stderr, "%d %s\n", err, FT_Error_String(err));
        return EXIT_FAILURE;
    }

    // 设置尺寸
    FT_UInt font_size = atoi(argv[2]) == 0 ? 16 : atoi(argv[2]);
    err = FT_Set_Pixel_Sizes(face, 0, font_size);
    if (err != FT_Err_Ok)
    {
        fprintf(stderr, "%d %s\n", err, FT_Error_String(err));
        return EXIT_FAILURE;
    }

    // 分配保存字形需要的内存
    size_t width = (size_t)(face->size->metrics.max_advance / 64);
    size_t height =  (size_t)(face->size->metrics.ascender - face->size->metrics.descender) / 64;
    size_t size = width * height;
    uint8_t* bitmap = (uint8_t*)malloc(size * ASCII_MAX);
    memset(bitmap, 0, size * ASCII_MAX);

    for (size_t ch = 0; ch < ASCII_MAX; ch++)
    {
        FT_UInt index = FT_Get_Char_Index(face, (FT_ULong)ch);
        FT_Load_Glyph(face, index, FT_LOAD_RENDER);

        // 渲染
        FT_Render_Glyph(face->glyph, FT_RENDER_MODE_NORMAL);

        ptrdiff_t offset = size * ch;
        ptrdiff_t top = (face->size->metrics.ascender/64 - face->glyph->bitmap_top);
        ptrdiff_t left = face->glyph->bitmap_left / 64;

        for (ptrdiff_t y = 0; y < face->glyph->bitmap.rows; y++)
        {
            for (ptrdiff_t x = 0; x < face->glyph->bitmap.width; x++)
            {
                bitmap[offset + (top+y) * width + (left+x)] = face->glyph->bitmap.buffer[y * face->glyph->bitmap.width + x];
            }
        }
    }

    FILE* preview = fopen("preview.ppm", "wb");
    fprintf(preview, "P5\n%zu %zu 255\n", width, height * ASCII_MAX);
    fwrite(bitmap, size * ASCII_MAX, 1, preview);
    fclose(preview);

    FILE* header = fopen("ascii_font.h", "wb");
    fprintf(header, "// Generated by: %s %s %s\n", argv[0], argv[1], argv[2]);
    fprintf(header, "// See: https://github.com/hubenchang0515/ascii_font\n");
    fprintf(header, "#ifndef ASCII_FONT_H\n");
    fprintf(header, "#define ASCII_FONT_H\n");
    fprintf(header, "\n");
    fprintf(header, "#define ASCII_FONT_WIDTH  %zu\n", width);
    fprintf(header, "#define ASCII_FONT_HEIGHT %zu\n", height);
    fprintf(header, "\n");
    fprintf(header, "#ifndef ASCII_FONT_IMPLEMENTATION\n");
    fprintf(header, "    unsigned char ascii_font[][ASCII_FONT_HEIGHT][ASCII_FONT_WIDTH];\n");
    fprintf(header, "#else\n");
    fprintf(header, "    unsigned char ascii_font[][ASCII_FONT_HEIGHT][ASCII_FONT_WIDTH] = \n");
    fprintf(header, "    {\n");
    for (size_t ch = 0; ch < ASCII_MAX; ch++)
    {
        size_t offset = size * ch;
        fprintf(header, "        {\n");
        for (size_t y = 0; y < height; y++)
        {
            fprintf(header, "            {");
            for (size_t x = 0; x < width; x++)
            {
                fprintf(header, "%u, ", (unsigned) bitmap[offset + y * width + x]);
            }
            fprintf(header, "},\n");
        }
        fprintf(header, "        },\n");
    }
    fprintf(header, "    };\n");
    fprintf(header, "#endif  // ASCII_FONT_IMPLEMENTATION\n");
    fprintf(header, "\n");
    fprintf(header, "#endif // ASCII_FONT_H\n");
    fclose(header);

    free(bitmap);
    FT_Done_Face(face);
    FT_Done_FreeType(library);

    return EXIT_SUCCESS;
}